/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BlipCapturePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var BLIPS_FILE = "Blips.md";
function padTwo(value) {
  return value < 10 ? `0${value}` : `${value}`;
}
function formatBlipLine(blip) {
  return `- **${blip.content}** ${blip.date}`;
}
var BlipCapturePlugin = class extends import_obsidian.Plugin {
  onload() {
    this.addRibbonIcon("zap", "Capture blip", () => {
      new BlipModal(this.app, this).open();
    });
    this.addRibbonIcon("list", "Manage blips", () => {
      new ManageBlipsModal(this.app, this).open();
    });
    this.addRibbonIcon("dice", "Random blip", () => {
      new RandomBlipModal(this.app, this).open();
    });
    this.addCommand({
      id: "capture-blip",
      name: "Capture a new blip",
      callback: () => {
        new BlipModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "manage-blips",
      name: "Manage blips (view and delete)",
      callback: () => {
        new ManageBlipsModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "random-blip",
      name: "Show a random blip",
      callback: () => {
        new RandomBlipModal(this.app, this).open();
      }
    });
  }
  async saveBlip(content) {
    const date = this.formatDate(new Date());
    const blipEntry = `- **${content}** ${date}`;
    const file = this.app.vault.getAbstractFileByPath(BLIPS_FILE);
    if (file instanceof import_obsidian.TFile) {
      const existingContent = await this.app.vault.read(file);
      const trimmed = existingContent.replace(/^\s+/, "");
      await this.app.vault.modify(file, `
${blipEntry}
${trimmed}`);
    } else {
      await this.app.vault.create(BLIPS_FILE, `
${blipEntry}`);
    }
    new import_obsidian.Notice("Blip saved");
  }
  async getBlips() {
    const file = this.app.vault.getAbstractFileByPath(BLIPS_FILE);
    if (!(file instanceof import_obsidian.TFile)) {
      return [];
    }
    const content = await this.app.vault.cachedRead(file);
    const blips = [];
    const lines = content.split("\n").filter((line) => line.trim() !== "");
    const blipPattern = /^-\s+\*\*(.+)\*\*\s+(\d{2}\/\d{2}\/\d{2})$/;
    let index = 0;
    for (const line of lines) {
      const match = blipPattern.exec(line);
      if (match) {
        blips.push({
          content: match[1].trim(),
          date: match[2],
          index: index++
        });
      }
    }
    return blips;
  }
  async deleteBlip(blipIndex) {
    const file = this.app.vault.getAbstractFileByPath(BLIPS_FILE);
    if (!(file instanceof import_obsidian.TFile)) {
      return;
    }
    const blips = await this.getBlips();
    const remainingBlips = blips.filter((_, i) => i !== blipIndex);
    await this.app.vault.modify(file, this.serializeBlips(remainingBlips));
    new import_obsidian.Notice("Blip deleted");
  }
  async reorderBlips(blips) {
    const file = this.app.vault.getAbstractFileByPath(BLIPS_FILE);
    if (!(file instanceof import_obsidian.TFile)) {
      return;
    }
    await this.app.vault.modify(file, this.serializeBlips(blips));
    new import_obsidian.Notice("Blips reordered");
  }
  serializeBlips(blips) {
    return `
${blips.map(formatBlipLine).join("\n")}`;
  }
  formatDate(date) {
    const month = padTwo(date.getMonth() + 1);
    const day = padTwo(date.getDate());
    const year = `${date.getFullYear()}`.slice(-2);
    return `${month}/${day}/${year}`;
  }
};
var BlipModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("blip-modal");
    contentEl.createEl("h3", { text: "Capture blip", cls: "blip-title" });
    this.textArea = contentEl.createEl("textarea", {
      cls: "blip-textarea",
      attr: {
        placeholder: "Type your blip here...",
        rows: "5"
      }
    });
    const buttonContainer = contentEl.createDiv({ cls: "blip-button-container" });
    const cancelButton = buttonContainer.createEl("button", {
      text: "Cancel",
      cls: "blip-button blip-cancel"
    });
    cancelButton.addEventListener("click", () => {
      this.close();
    });
    const saveButton = buttonContainer.createEl("button", {
      text: "Save",
      cls: "blip-button blip-save"
    });
    saveButton.addEventListener("click", () => {
      void this.saveBlip();
    });
    this.textArea.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) {
        e.preventDefault();
        void this.saveBlip();
      }
      if (e.key === "Escape") {
        this.close();
      }
    });
    this.textArea.focus();
  }
  async saveBlip() {
    const content = this.textArea.value.trim();
    if (!content) {
      new import_obsidian.Notice("Please enter some content for your blip.");
      return;
    }
    await this.plugin.saveBlip(content);
    this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ManageBlipsModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.blips = [];
    this.draggedItem = null;
    this.draggedIndex = -1;
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("blip-modal");
    contentEl.addClass("blip-manage-modal");
    contentEl.createEl("h3", { text: "Manage blips", cls: "blip-title" });
    contentEl.createEl("p", {
      text: "Drag to reorder \u2022 Click \xD7 to delete",
      cls: "blip-instructions"
    });
    this.blipsContainer = contentEl.createDiv({ cls: "blips-list-container" });
    const buttonContainer = contentEl.createDiv({ cls: "blip-button-container" });
    const closeButton = buttonContainer.createEl("button", {
      text: "Close",
      cls: "blip-button blip-cancel"
    });
    closeButton.addEventListener("click", () => {
      this.close();
    });
    void this.renderBlips();
  }
  async renderBlips() {
    this.blipsContainer.empty();
    this.blips = await this.plugin.getBlips();
    if (this.blips.length === 0) {
      this.blipsContainer.createEl("p", {
        text: "No blips yet.",
        cls: "blip-empty-message"
      });
      return;
    }
    for (let i = 0; i < this.blips.length; i++) {
      const blip = this.blips[i];
      const blipItem = this.blipsContainer.createDiv({ cls: "blip-item" });
      blipItem.setAttribute("draggable", "true");
      blipItem.dataset.index = String(i);
      const dragHandle = blipItem.createDiv({ cls: "blip-drag-handle" });
      dragHandle.setText("\u22EE\u22EE");
      const blipContent = blipItem.createDiv({ cls: "blip-item-content" });
      blipContent.createDiv({
        text: blip.content.length > 80 ? `${blip.content.substring(0, 80)}...` : blip.content,
        cls: "blip-item-text"
      });
      blipContent.createDiv({
        text: blip.date,
        cls: "blip-item-date"
      });
      const deleteButton = blipItem.createEl("button", {
        text: "\xD7",
        cls: "blip-delete-button",
        attr: { "aria-label": "Delete blip" }
      });
      deleteButton.addEventListener("click", (e) => {
        e.stopPropagation();
        void this.removeBlip(i);
      });
      blipItem.addEventListener("dragstart", (e) => {
        this.handleDragStart(e, i);
      });
      blipItem.addEventListener("dragend", () => {
        this.handleDragEnd();
      });
      blipItem.addEventListener("dragover", (e) => {
        this.handleDragOver(e);
      });
      blipItem.addEventListener("drop", (e) => {
        void this.handleDrop(e, i);
      });
      blipItem.addEventListener("dragenter", (e) => {
        this.handleDragEnter(e);
      });
      blipItem.addEventListener("dragleave", (e) => {
        this.handleDragLeave(e);
      });
    }
  }
  async removeBlip(index) {
    await this.plugin.deleteBlip(index);
    await this.renderBlips();
  }
  handleDragStart(e, index) {
    this.draggedIndex = index;
    this.draggedItem = e.target;
    this.draggedItem.addClass("blip-dragging");
    if (e.dataTransfer) {
      e.dataTransfer.effectAllowed = "move";
      e.dataTransfer.setData("text/plain", String(index));
    }
  }
  handleDragEnd() {
    if (this.draggedItem) {
      this.draggedItem.removeClass("blip-dragging");
    }
    this.draggedItem = null;
    this.draggedIndex = -1;
    const items = this.blipsContainer.querySelectorAll(".blip-item");
    items.forEach((item) => {
      item.removeClass("blip-drag-over");
    });
  }
  handleDragOver(e) {
    e.preventDefault();
    if (e.dataTransfer) {
      e.dataTransfer.dropEffect = "move";
    }
  }
  handleDragEnter(e) {
    const target = e.target.closest(".blip-item");
    if (target && target !== this.draggedItem) {
      target.addClass("blip-drag-over");
    }
  }
  handleDragLeave(e) {
    const target = e.target.closest(".blip-item");
    if (target) {
      target.removeClass("blip-drag-over");
    }
  }
  async handleDrop(e, dropIndex) {
    e.preventDefault();
    if (this.draggedIndex === -1 || this.draggedIndex === dropIndex) {
      return;
    }
    const draggedBlip = this.blips[this.draggedIndex];
    this.blips.splice(this.draggedIndex, 1);
    this.blips.splice(dropIndex, 0, draggedBlip);
    await this.plugin.reorderBlips(this.blips);
    await this.renderBlips();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var RandomBlipModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.blips = [];
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("blip-modal");
    contentEl.addClass("blip-random-modal");
    contentEl.createEl("h3", { text: "Random blip", cls: "blip-title" });
    this.blipDisplay = contentEl.createDiv({ cls: "random-blip-display" });
    const buttonContainer = contentEl.createDiv({ cls: "blip-button-container" });
    const anotherButton = buttonContainer.createEl("button", {
      text: "Another",
      cls: "blip-button blip-save"
    });
    anotherButton.addEventListener("click", () => {
      this.showRandomBlip();
    });
    const closeButton = buttonContainer.createEl("button", {
      text: "Close",
      cls: "blip-button blip-cancel"
    });
    closeButton.addEventListener("click", () => {
      this.close();
    });
    void this.loadBlips();
  }
  async loadBlips() {
    this.blips = await this.plugin.getBlips();
    this.showRandomBlip();
  }
  showRandomBlip() {
    this.blipDisplay.empty();
    if (this.blips.length === 0) {
      this.blipDisplay.createEl("p", {
        text: "No blips yet.",
        cls: "blip-empty-message"
      });
      return;
    }
    const randomIndex = Math.floor(Math.random() * this.blips.length);
    const blip = this.blips[randomIndex];
    this.blipDisplay.createDiv({
      text: blip.content,
      cls: "random-blip-content"
    });
    this.blipDisplay.createDiv({
      text: blip.date,
      cls: "random-blip-date"
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
